image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - apk add make
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHA}" all
    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHA}" push
    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHA}" push-short
    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHA}" push-latest

integration:
  stage: test
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]tests?\]/i
    - $SKIP_TESTS
  services:
    - docker:dind
  image: docker:stable
  script:
    - apk add make bash jq
    - make REGISTRY="${CI_REGISTRY_IMAGE}" VERSION="${CI_COMMIT_SHA}" test


release:
  stage: release
  only:
    - tags
  script:
    - apk add make
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

    - make VERSION="${CI_COMMIT_TAG#v}" all
    - make VERSION="${CI_COMMIT_TAG#v}" push
    - make VERSION="${CI_COMMIT_TAG#v}" push-short
    - make VERSION="${CI_COMMIT_TAG#v}" push-latest
