image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release

build_image:
  stage: build
  script:
    - apk add make bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

    - make REGISTRY="${CI_REGISTRY_IMAGE}" TAG="${CI_COMMIT_SHA}" build
    - make REGISTRY="${CI_REGISTRY_IMAGE}" TAG="${CI_COMMIT_SHA}" push

integration:
  stage: test
  services:
    - docker:dind
  image: docker:stable
  script:
    - apk add make bash jq
    - make REGISTRY="${CI_REGISTRY_IMAGE}" TAG="${CI_COMMIT_SHA}" test


release_image:
  stage: release
  only:
    - tags
  script:
    - apk add make bash
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

    - make REGISTRY="nvidia" TAG="${CI_COMMIT_TAG}" build
    - make REGISTRY="nvidia" TAG="${CI_COMMIT_TAG}" push
